# Custom Language File for Launcher Customizer

[ejs.app]
title = "Exe And Chill Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Xenows76/Exe-And-Chill"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.com/invite/dFZDtjrpwE"

[ejs.settings]
sourceGithubLink = "https://github.com/Xenows76/Exe-And-Chill"
supportLink = "https://github.com/Xenows76/Exe-And-Chill/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR EXE AND CHILL"
welcomeDescription = "Votre aventure de dresseur commence ici, conquis le monde et capture le plus de pokémon"
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de Exe And Chill."
